### PR TITLE
restoring ItemNumber

### PR DESCRIPTION
**Pull request by pmgreen**

### CODE REVIEW

**Review by mzelesky — CHANGES_REQUESTED** [review]
The code from lines 316 through 332 is the code I was unable to get to work. I don't think it affects lending either. I would suggest only making the changes to the lending side.

**Comment by pmgreen** [comment]
The pickup location code (316-332) has been there since go-live. If it's not doing anything we can probably safely take it out and replace it with the vcu code, but removing them does represent a change to working code.

**Comment by mzelesky** [comment]
When we had the new pickup location code in place on Liza's computer, it failed. When we switched to the vcu code, it worked.

**Comment by mzelesky** [comment]
Also, borrowing is currently working.

**Comment by pmgreen** [comment]
Testing may have been done using various versions of the lua file. I'll defer to @mzelesky and @kevinreiss on pickup location lines. Just making a note here that they were in the working lua file at go-live, at least on Nick's machine, so I'd be inclined to leave them.

**Review by kevinreiss — APPROVED** [review]

**Review by mzelesky — APPROVED** [review]
Lending and borrowing worked on Nick's computer.

**Review by kevinreiss — APPROVED** [review]

**Pull request merged**
